test_suites:
- name: lint
  job_name: lint
  script_path: /root/okta/amd-to-es6/scripts
  sort_order: '0'
  timeout: '10'
  script_name: lint
  script_env: {
    }
  criteria: MERGE
  queue_name: small
- name: test
  job_name: test
  script_path: /root/okta/amd-to-es6/scripts
  sort_order: '1'
  timeout: '20'
  script_name: test
  script_env: {
    }
  criteria: MERGE
  queue_name: ci-queue-productionJenga-Selenium-Small
- name: publish
  job_name: publish
  script_path: /root/okta/amd-to-es6/scripts
  sort_order: '2'
  timeout: '10'
  script_name: publish
  script_env: {
    }
  criteria: MERGE
  queue_name: small
